# Standard music file for 6-bell compositions

[[music]]
run_lengths = [4, 5, 6]

[[music]]
pattern = "*56"

[[music]]
patterns = ["135246", "342516", "142536"] # Queens, exploded tittums and tittums
weight = 4
