# Standard music file for 8-bell compositions

[[music]]
run_lengths = [4, 5, 6, 7, 8]

[[music]]
patterns = [
    "6578*", "*6578",
    "5678*", "*5678",
    "8765*", "*8765",
]

[[music]]
pattern = "13572468"
weight = 3
