length = "QP"
course_heads = ["1xxx87xx", "1xxx5678"]
base_calls = "none" # We need custom calls (12 bobs, 1234 singles)
snap_start = true
music_file = "music-8.toml"


[method]
name = "Cornnroc"
place_notation = "x5x4x5x1x4x5x4x5,4"
stage = 8


[[calls]]
debug_symbol = "-"
symbol = ""
place_notation = "12"

[[calls]]
symbol = "s"
place_notation = "1234"
